vim.lsp.config("gopls", {
    settings = {
        gopls = {
            analyses = {
                composites = true,
                nilness = true,
                unusedparams = true,
                unusedwrite = true,
                useany = true,
                shadow = true,
                unusedvariable = true,
                appends = true,
                defers = true,
                deprecated = true,
                directive = true,
                embed = true,
                errorsas = true,
                httpresponse = true,
                ifaceassert = true,
                loopclosure = true,
                lostcancel = true,
                nilfunc = true,
                sortslice = true,
                stringintconv = true,
                testinggoroutine = true,
                timeformat = true,
                unmarshal = true,
                unreachable = true,
                fillreturns = true,
                nonewvars = true,
                noresultvalues = true,
                undeclaredname = true,
            },
            staticcheck = true,
        },
    },
})
